version: "3"
services:
    life-helper-service:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/inlym/lifehelper_server:2.3.0
        ports:
            - "23030:23030"
        environment:
            - a=aaa

    # MySQL - 仅本地开发环境使用
    life-helper-mysql:
        image: mysql:8.0.37
        ports:
            - "3306:3306"
        environment:
            # root 账户密码
            - MYSQL_ROOT_PASSWORD=123456

    # Redis - 仅本地开发环境使用
    life-helper-redis:
        image: redis:7.2
        ports:
            - "6379:6379"
