spring:
    profiles:
        # 启用的环境，目前包含 dev 和 prod
        active: dev
    main:
        # 关闭启动 Banner
        banner-mode: off
        # 关闭延迟初始化
        lazy-initialization: false
    jackson:
        # 时区
        time-zone: GMT+8
        # 日期格式化
        date-format: yyyy-MM-dd HH:mm:ss
        # 返回响应移除 null 值字段
        default-property-inclusion: non_null
