# 当前文件仅用于演示 application-dev.yml 和 application-prod.yml 的文件格式

server:
    # Web 监听端口
    port: 8080

spring:
    # Redis 配置
    redis:
        host: xxxxxxxxxxxx
        database: 0
        port: 6379
        password: xxxxxxxxxxxx
        connect-timeout: 1000
        timeout: 20000
        lettuce:
            pool:
                # 连接池最大的活动连接数
                max-active: 20
                # 连接池最大空闲连接数
                max-idle: 20
                # 连接池最小空闲连接数
                min-idle: 2

    # MySQL 数据库配置
    datasource:
        url: jdbc:mysql://localhost:3306/lifehelper_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: xxxxxxxxxxxx
        password: xxxxxxxxxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver

# 日志
logging:
    # 日志等级
    level:
        com.inlym.lifehelper: debug

# 项目配置
lifehelper:
    # 网页端 URL 地址
    web-url: https://www.lifehelper.com.cn

    # 权限相关
    auth:
        # JSON Web Token
        jwt:
            # JWT 密钥
            secret: xxxxxxxxxxxx

    # 腾讯位置服务
    tencent-map:
        # 开发者密钥
        keys:
            - xxxxxxxxxxxx
            - xxxxxxxxxxxx
            - xxxxxxxxxxxx

    # 和风天气
    he-weather:
        dev-key: xxxxxxxxxxxx
        pro-key: xxxxxxxxxxxx

    # 微信小程序服务端配置
    weixin:
        appid: xxxxxxxxxxxx
        secret: xxxxxxxxxxxx

# 阿里云资源配置
aliyun:
    # 阿里云 OSS 配置
    oss:
        access-key-id: xxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxx
        # 访问域名
        endpoint: xxxxxxxxxxxx
        # 存储空间名称
        bucket-name: xxxxxxxxxxxx
        # 绑定的自定义域名（包含 https:// 前缀部分）
        alias-url: xxxxxxxxxxxx

    # 阿里云表格存储配置
    tablestore:
        # 宽表模型
        wide-column:
            access-key-id: xxxxxxxxxxxx
            access-key-secret: xxxxxxxxxxxx
            endpoint: xxxxxxxxxxxx
            instance-name: xxxxxxxxxxxx
