spring:
    profiles:
        # 启用的环境，目前包含 dev 和 prod
        active: dev

    main:
        # 关闭启动 Banner
        banner-mode: off
        # 关闭延迟初始化
        lazy-initialization: false

    jackson:
        # 时区
        time-zone: GMT+8
        # 日期格式化
        date-format: yyyy-MM-dd HH:mm:ss
        # 返回响应移除 null 值字段
        default-property-inclusion: non_null

    # 缓存配置
    cache:
        type: redis

    # Spring Security 配置
    security:
        filter:
            # 鉴权过滤器排序
            order: 10000

    # 数据源配置
    datasource:
        # Alibaba Druid
        druid:
            filter:
                # 配置 StatFilter
                stat:
                    enabled: true
                    log-slow-sql: true
                    slow-sql-millis: 1000
                # 配置 WallFilter
                wall:
                    enabled: true
                    config:
                        delete-allow: false
                        drop-table-allow: false
            keep-alive: true
            # 初始化大小
            initial-size: 5
            min-idle: 10
            max-active: 20
            # 获取连接等待超时的时间
            max-wait: 6000
