# 当前文件仅用于演示 application-dev.yml 和 application-prod.yml 的文件格式

server:
    # Web 监听端口
    port: 8080

spring:
    data:
        # Redis 配置
        redis:
            host: xxxxxxxxxxxx
            database: 0
            port: 6379
            password: xxxxxxxxxxxx
            connect-timeout: 1000
            timeout: 20000

    # MySQL 数据库配置
    datasource:
        url: jdbc:mysql://localhost:3306/lifehelper_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: xxxxxxxxxxxx
        password: xxxxxxxxxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver

    # 阿里云分布式任务调度平台 SchedulerX 配置
    # 文档：https://help.aliyun.com/document_detail/161998.html?userCode=lzfqdh6g
    schedulerx2:
        endpoint: "acm.aliyun.com"
        namespace: "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        groupId: xxxxxxxxxxxx
        appKey: xxxxxxxxxxxx


# 日志
logging:
    # 日志等级
    level:
        com.inlym.lifehelper: debug

# 项目配置
lifehelper:
    # 版本号（该值由项目启动时传入，此处定义仅供展示该字段）
    version: "0.0.0"

    # 腾讯位置服务
    we-map:
        # 开发者密钥
        key: xxxxxxxxxxxx

    # 和风天气
    he-weather:
        key: xxxxxxxxxxxx

    # 微信小程序配置
    wechat:
        # 【小鸣助手】小程序
        main-app:
            app-id: xxxxxxxxxxxx
            app-secret: xxxxxxxxxxxx
        # 【小鸣 AI】小程序
        ai-app:
            app-id: xxxxxxxxxxxx
            app-secret: xxxxxxxxxxxx
        # 【小鸣天气】小程序
        weather-app:
            app-id: xxxxxxxxxxxx
            app-secret: xxxxxxxxxxxx


    # ChatGPT
    openai:
        # 请求地址前缀部分
        base-url: xxxxxxxxxxxx
        # 开发者密钥
        key: xxxxxxxxxxxx


# 阿里云资源配置
aliyun:
    # 阿里云 OSS 配置
    oss:
        main:
            # AccessKey ID
            access-key-id: xxxxxxxxxxxx
            # AccessKey Secret
            access-key-secret: xxxxxxxxxxxx
            # 访问域名
            endpoint: xxxxxxxxxxxx
            # 存储空间名称
            bucket-name: xxxxxxxxxxxx
            # 绑定的自定义域名（包含 https:// 前缀部分）
            alias-url: xxxxxxxxxxxx
        ugc:
            # AccessKey ID
            access-key-id: xxxxxxxxxxxx
            # AccessKey Secret
            access-key-secret: xxxxxxxxxxxx
            # 访问域名
            endpoint: xxxxxxxxxxxx
            # 存储空间名称
            bucket-name: xxxxxxxxxxxx
            # 绑定的自定义域名（包含 https:// 前缀部分）
            alias-url: xxxxxxxxxxxx

    # 阿里云表格存储配置
    ots:
        # 宽表模型
        wide-column:
            access-key-id: xxxxxxxxxxxx
            access-key-secret: xxxxxxxxxxxx
            endpoint: xxxxxxxxxxxx
            instance-name: xxxxxxxxxxxx

    # 阿里云日志服务配置
    sls:
        access-key-id: xxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxx
        endpoint: xxxxxxxxxxxx
        project: xxxxxxxxxxxx
        log-store: xxxxxxxxxxxx

    # 短信服务
    sms:
        access-key-id: xxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxx
