# ========================== 文件说明 ==========================
# 当前文件仅用于演示对应配置文件的格式，请将 xxxxxxxxxxxx 替换为实际的值，并改名为 `application-dev.yml` 或 `application-prod.yml`

# ======================== 以下是配置内容 ========================

server: # Web 监听端口
    port: 8080

spring:
    data: # Redis 配置
        redis:
            host: xxxxxxxxxxxx
            database: 0
            port: 6379
            password: xxxxxxxxxxxx
            connect-timeout: 1000
            timeout: 20000

    datasource:
        url: jdbc:mysql://localhost:3306/lifehelper_db_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: xxxxxxxxxxxx
        password: xxxxxxxxxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver
