# ========================== 文件说明 ==========================
# 当前文件仅用于演示对应配置文件的格式，请将 xxxxxxxxxxxx 替换为实际的值，并去掉文件名的 `-demo` 部分

# ======================== 以下是配置内容 ========================

# 腾讯位置服务
wemap:
    # 开发者密钥
    key: xxxxxxxxxxxx
